//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTwo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatTwo.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + {0}.
        /// </summary>
        internal static string AutoTranslate_Completion_Key {
            get {
                return ResourceManager.GetString("AutoTranslate_Completion_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Auto Translate....
        /// </summary>
        internal static string AutoTranslate_Search_Hint {
            get {
                return ResourceManager.GetString("AutoTranslate_Search_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide chat.
        /// </summary>
        internal static string ChatLog_HideChat {
            get {
                return ResourceManager.GetString("ChatLog_HideChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled for this tab..
        /// </summary>
        internal static string ChatLog_SwitcherDisabled {
            get {
                return ResourceManager.GetString("ChatLog_SwitcherDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tab.
        /// </summary>
        internal static string ChatLog_Tabs_Delete {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string ChatLog_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        internal static string ChatLog_Tabs_MoveLeft {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        internal static string ChatLog_Tabs_MoveRight {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string ChatLog_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop out.
        /// </summary>
        internal static string ChatLog_Tabs_PopOut {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_PopOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Member.
        /// </summary>
        internal static string ChatSource_AllianceMember {
            get {
                return ResourceManager.GetString("ChatSource_AllianceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Alliance member).
        /// </summary>
        internal static string ChatSource_AlliancePet {
            get {
                return ResourceManager.GetString("ChatSource_AlliancePet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged Enemy.
        /// </summary>
        internal static string ChatSource_EngagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_EngagedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly NPC.
        /// </summary>
        internal static string ChatSource_FriendlyNpc {
            get {
                return ResourceManager.GetString("ChatSource_FriendlyNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ChatSource_Other {
            get {
                return ResourceManager.GetString("ChatSource_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Other).
        /// </summary>
        internal static string ChatSource_OtherPet {
            get {
                return ResourceManager.GetString("ChatSource_OtherPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Member.
        /// </summary>
        internal static string ChatSource_PartyMember {
            get {
                return ResourceManager.GetString("ChatSource_PartyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Party).
        /// </summary>
        internal static string ChatSource_PartyPet {
            get {
                return ResourceManager.GetString("ChatSource_PartyPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string ChatSource_Self {
            get {
                return ResourceManager.GetString("ChatSource_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Self).
        /// </summary>
        internal static string ChatSource_SelfPet {
            get {
                return ResourceManager.GetString("ChatSource_SelfPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unengaged Enemy.
        /// </summary>
        internal static string ChatSource_UnengagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_UnengagedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions used.
        /// </summary>
        internal static string ChatType_Action {
            get {
                return ResourceManager.GetString("ChatType_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Notifications.
        /// </summary>
        internal static string ChatType_Alarm {
            get {
                return ResourceManager.GetString("ChatType_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string ChatType_Alliance {
            get {
                return ResourceManager.GetString("ChatType_Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle System Messages.
        /// </summary>
        internal static string ChatType_BattleSystem {
            get {
                return ResourceManager.GetString("ChatType_BattleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesis Messages.
        /// </summary>
        internal static string ChatType_Crafting {
            get {
                return ResourceManager.GetString("ChatType_Crafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [1].
        /// </summary>
        internal static string ChatType_CrossLinkshell1 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [2].
        /// </summary>
        internal static string ChatType_CrossLinkshell2 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [3].
        /// </summary>
        internal static string ChatType_CrossLinkshell3 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [4].
        /// </summary>
        internal static string ChatType_CrossLinkshell4 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [5].
        /// </summary>
        internal static string ChatType_CrossLinkshell5 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [6].
        /// </summary>
        internal static string ChatType_CrossLinkshell6 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [7].
        /// </summary>
        internal static string ChatType_CrossLinkshell7 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Linkshell [8].
        /// </summary>
        internal static string ChatType_CrossLinkshell8 {
            get {
                return ResourceManager.GetString("ChatType_CrossLinkshell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-world Party.
        /// </summary>
        internal static string ChatType_CrossWorldParty {
            get {
                return ResourceManager.GetString("ChatType_CrossWorldParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Emotes.
        /// </summary>
        internal static string ChatType_CustomEmotes {
            get {
                return ResourceManager.GetString("ChatType_CustomEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage dealt.
        /// </summary>
        internal static string ChatType_Damage {
            get {
                return ResourceManager.GetString("ChatType_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string ChatType_Debug {
            get {
                return ResourceManager.GetString("ChatType_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        internal static string ChatType_Echo {
            get {
                return ResourceManager.GetString("ChatType_Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Messages.
        /// </summary>
        internal static string ChatType_Error {
            get {
                return ResourceManager.GetString("ChatType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string ChatType_FreeCompany {
            get {
                return ResourceManager.GetString("ChatType_FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Announcements.
        /// </summary>
        internal static string ChatType_FreeCompanyAnnouncement {
            get {
                return ResourceManager.GetString("ChatType_FreeCompanyAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Member Login Notifications.
        /// </summary>
        internal static string ChatType_FreeCompanyLoginLogout {
            get {
                return ResourceManager.GetString("ChatType_FreeCompanyLoginLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial effects granted.
        /// </summary>
        internal static string ChatType_GainBuff {
            get {
                return ResourceManager.GetString("ChatType_GainBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detrimental effects inflicted.
        /// </summary>
        internal static string ChatType_GainDebuff {
            get {
                return ResourceManager.GetString("ChatType_GainDebuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Messages.
        /// </summary>
        internal static string ChatType_Gathering {
            get {
                return ResourceManager.GetString("ChatType_Gathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering System Messages.
        /// </summary>
        internal static string ChatType_GatheringSystem {
            get {
                return ResourceManager.GetString("ChatType_GatheringSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company (GM).
        /// </summary>
        internal static string ChatType_GmFreeCompany {
            get {
                return ResourceManager.GetString("ChatType_GmFreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [1] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell1 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [2] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell2 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [3] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell3 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [4] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell4 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [5] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell5 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [6] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell6 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [7] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell7 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [8] (GM).
        /// </summary>
        internal static string ChatType_GmLinkshell8 {
            get {
                return ResourceManager.GetString("ChatType_GmLinkshell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Network (GM).
        /// </summary>
        internal static string ChatType_GmNoviceNetwork {
            get {
                return ResourceManager.GetString("ChatType_GmNoviceNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party (GM).
        /// </summary>
        internal static string ChatType_GmParty {
            get {
                return ResourceManager.GetString("ChatType_GmParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say (GM).
        /// </summary>
        internal static string ChatType_GmSay {
            get {
                return ResourceManager.GetString("ChatType_GmSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout (GM).
        /// </summary>
        internal static string ChatType_GmShout {
            get {
                return ResourceManager.GetString("ChatType_GmShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell (GM).
        /// </summary>
        internal static string ChatType_GmTell {
            get {
                return ResourceManager.GetString("ChatType_GmTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell (GM).
        /// </summary>
        internal static string ChatType_GmYell {
            get {
                return ResourceManager.GetString("ChatType_GmYell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string ChatType_Healing {
            get {
                return ResourceManager.GetString("ChatType_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items used.
        /// </summary>
        internal static string ChatType_Item {
            get {
                return ResourceManager.GetString("ChatType_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [1].
        /// </summary>
        internal static string ChatType_Linkshell1 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [2].
        /// </summary>
        internal static string ChatType_Linkshell2 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [3].
        /// </summary>
        internal static string ChatType_Linkshell3 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [4].
        /// </summary>
        internal static string ChatType_Linkshell4 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [5].
        /// </summary>
        internal static string ChatType_Linkshell5 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [6].
        /// </summary>
        internal static string ChatType_Linkshell6 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [7].
        /// </summary>
        internal static string ChatType_Linkshell7 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell [8].
        /// </summary>
        internal static string ChatType_Linkshell8 {
            get {
                return ResourceManager.GetString("ChatType_Linkshell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Notices.
        /// </summary>
        internal static string ChatType_LootNotice {
            get {
                return ResourceManager.GetString("ChatType_LootNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Messages.
        /// </summary>
        internal static string ChatType_LootRoll {
            get {
                return ResourceManager.GetString("ChatType_LootRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial effects lost.
        /// </summary>
        internal static string ChatType_LoseBuff {
            get {
                return ResourceManager.GetString("ChatType_LoseBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detrimental effects cured.
        /// </summary>
        internal static string ChatType_LoseDebuff {
            get {
                return ResourceManager.GetString("ChatType_LoseDebuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Book Alert.
        /// </summary>
        internal static string ChatType_MessageBook {
            get {
                return ResourceManager.GetString("ChatType_MessageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed attacks.
        /// </summary>
        internal static string ChatType_Miss {
            get {
                return ResourceManager.GetString("ChatType_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string ChatType_Notice {
            get {
                return ResourceManager.GetString("ChatType_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Network.
        /// </summary>
        internal static string ChatType_NoviceNetwork {
            get {
                return ResourceManager.GetString("ChatType_NoviceNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Network Announcements.
        /// </summary>
        internal static string ChatType_NoviceNetworkSystem {
            get {
                return ResourceManager.GetString("ChatType_NoviceNetworkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Dialogue (Announcements).
        /// </summary>
        internal static string ChatType_NpcAnnouncement {
            get {
                return ResourceManager.GetString("ChatType_NpcAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Dialogue.
        /// </summary>
        internal static string ChatType_NpcDialogue {
            get {
                return ResourceManager.GetString("ChatType_NpcDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Orchestrion Track Messages.
        /// </summary>
        internal static string ChatType_Orchestrion {
            get {
                return ResourceManager.GetString("ChatType_Orchestrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string ChatType_Party {
            get {
                return ResourceManager.GetString("ChatType_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Recruitment Notifications.
        /// </summary>
        internal static string ChatType_PeriodicRecruitmentNotification {
            get {
                return ResourceManager.GetString("ChatType_PeriodicRecruitmentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression Messages.
        /// </summary>
        internal static string ChatType_Progress {
            get {
                return ResourceManager.GetString("ChatType_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Team.
        /// </summary>
        internal static string ChatType_PvpTeam {
            get {
                return ResourceManager.GetString("ChatType_PvpTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Team Announcements.
        /// </summary>
        internal static string ChatType_PvpTeamAnnouncement {
            get {
                return ResourceManager.GetString("ChatType_PvpTeamAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Team Member Login Notifications.
        /// </summary>
        internal static string ChatType_PvpTeamLoginLogout {
            get {
                return ResourceManager.GetString("ChatType_PvpTeamLoginLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Number Messages.
        /// </summary>
        internal static string ChatType_RandomNumber {
            get {
                return ResourceManager.GetString("ChatType_RandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainer Sale Notifications.
        /// </summary>
        internal static string ChatType_RetainerSale {
            get {
                return ResourceManager.GetString("ChatType_RetainerSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string ChatType_Say {
            get {
                return ResourceManager.GetString("ChatType_Say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string ChatType_Shout {
            get {
                return ResourceManager.GetString("ChatType_Shout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Messages for PC Targets.
        /// </summary>
        internal static string ChatType_Sign {
            get {
                return ResourceManager.GetString("ChatType_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Emotes.
        /// </summary>
        internal static string ChatType_StandardEmotes {
            get {
                return ResourceManager.GetString("ChatType_StandardEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Messages.
        /// </summary>
        internal static string ChatType_System {
            get {
                return ResourceManager.GetString("ChatType_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell (Incoming).
        /// </summary>
        internal static string ChatType_TellIncoming {
            get {
                return ResourceManager.GetString("ChatType_TellIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell (Outgoing).
        /// </summary>
        internal static string ChatType_TellOutgoing {
            get {
                return ResourceManager.GetString("ChatType_TellOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        internal static string ChatType_Urgent {
            get {
                return ResourceManager.GetString("ChatType_Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string ChatType_Yell {
            get {
                return ResourceManager.GetString("ChatType_Yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string CommandHelpSide_Left {
            get {
                return ResourceManager.GetString("CommandHelpSide_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CommandHelpSide_None {
            get {
                return ResourceManager.GetString("CommandHelpSide_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string CommandHelpSide_Right {
            get {
                return ResourceManager.GetString("CommandHelpSide_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Blacklist.
        /// </summary>
        internal static string Context_AddToBlacklist {
            get {
                return ResourceManager.GetString("Context_AddToBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Context_Copy {
            get {
                return ResourceManager.GetString("Context_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Item Name.
        /// </summary>
        internal static string Context_CopyItemName {
            get {
                return ResourceManager.GetString("Context_CopyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide chat.
        /// </summary>
        internal static string Context_HideChat {
            get {
                return ResourceManager.GetString("Context_HideChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        internal static string Context_Integrations {
            get {
                return ResourceManager.GetString("Context_Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite to Novice Network.
        /// </summary>
        internal static string Context_InviteToNoviceNetwork {
            get {
                return ResourceManager.GetString("Context_InviteToNoviceNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite to Party.
        /// </summary>
        internal static string Context_InviteToParty {
            get {
                return ResourceManager.GetString("Context_InviteToParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different world.
        /// </summary>
        internal static string Context_InviteToParty_DifferentWorld {
            get {
                return ResourceManager.GetString("Context_InviteToParty_DifferentWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same world.
        /// </summary>
        internal static string Context_InviteToParty_SameWorld {
            get {
                return ResourceManager.GetString("Context_InviteToParty_SameWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Comparison.
        /// </summary>
        internal static string Context_ItemComparison {
            get {
                return ResourceManager.GetString("Context_ItemComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick from Party.
        /// </summary>
        internal static string Context_KickFromParty {
            get {
                return ResourceManager.GetString("Context_KickFromParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Context_Link {
            get {
                return ResourceManager.GetString("Context_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        internal static string Context_Promote {
            get {
                return ResourceManager.GetString("Context_Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply in Selected Chat Mode.
        /// </summary>
        internal static string Context_ReplyInSelectedChatMode {
            get {
                return ResourceManager.GetString("Context_ReplyInSelectedChatMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot mode.
        /// </summary>
        internal static string Context_ScreenshotMode {
            get {
                return ResourceManager.GetString("Context_ScreenshotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Item.
        /// </summary>
        internal static string Context_SearchForItem {
            get {
                return ResourceManager.GetString("Context_SearchForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Recipes Using This Material.
        /// </summary>
        internal static string Context_SearchRecipes {
            get {
                return ResourceManager.GetString("Context_SearchRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        internal static string Context_SendFriendRequest {
            get {
                return ResourceManager.GetString("Context_SendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Tell.
        /// </summary>
        internal static string Context_SendTell {
            get {
                return ResourceManager.GetString("Context_SendTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Context_Target {
            get {
                return ResourceManager.GetString("Context_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try On.
        /// </summary>
        internal static string Context_TryOn {
            get {
                return ResourceManager.GetString("Context_TryOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (full).
        /// </summary>
        internal static string ExtraGlyphRanges_ChineseFull_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_ChineseFull_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (common simplified).
        /// </summary>
        internal static string ExtraGlyphRanges_ChineseSimplifiedCommon_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_ChineseSimplifiedCommon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic.
        /// </summary>
        internal static string ExtraGlyphRanges_Cyrillic_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Cyrillic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string ExtraGlyphRanges_Japanese_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Japanese_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string ExtraGlyphRanges_Korean_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Korean_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string ExtraGlyphRanges_Thai_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Thai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string ExtraGlyphRanges_Vietnamese_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Vietnamese_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible.
        /// </summary>
        internal static string KeybindMode_Flexible_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process keybinds with modifiers even if other modifiers are pressed..
        /// </summary>
        internal static string KeybindMode_Flexible_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        internal static string KeybindMode_Strict_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only process keybinds with modifiers if no other modifiers are pressed..
        /// </summary>
        internal static string KeybindMode_Strict_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dalamud&apos;s default language.
        /// </summary>
        internal static string LanguageOverride_None {
            get {
                return ResourceManager.GetString("LanguageOverride_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to the left to see what&apos;s being worked on and what&apos;s next..
        /// </summary>
        internal static string Options_About_ClickUp {
            get {
                return ResourceManager.GetString("Options_About_ClickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to the left to help translate {0}..
        /// </summary>
        internal static string Options_About_CrowdIn {
            get {
                return ResourceManager.GetString("Options_About_CrowdIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a project to completely recreate the in-game chat and make it even better..
        /// </summary>
        internal static string Options_About_Opening {
            get {
                return ResourceManager.GetString("Options_About_Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Options_About_Tab {
            get {
                return ResourceManager.GetString("Options_About_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        internal static string Options_About_Translators {
            get {
                return ResourceManager.GetString("Options_About_Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving chat.
        /// </summary>
        internal static string Options_CanMove_Name {
            get {
                return ResourceManager.GetString("Options_CanMove_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow resizing chat.
        /// </summary>
        internal static string Options_CanResize_Name {
            get {
                return ResourceManager.GetString("Options_CanResize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from game.
        /// </summary>
        internal static string Options_ChatColours_Import {
            get {
                return ResourceManager.GetString("Options_ChatColours_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        internal static string Options_ChatColours_Reset {
            get {
                return ResourceManager.GetString("Options_ChatColours_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat colours.
        /// </summary>
        internal static string Options_ChatColours_Tab {
            get {
                return ResourceManager.GetString("Options_ChatColours_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show the first message and show a counter at the end of messages that have been repeated..
        /// </summary>
        internal static string Options_CollapseDuplicateMessages_Description {
            get {
                return ResourceManager.GetString("Options_CollapseDuplicateMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse duplicate messages.
        /// </summary>
        internal static string Options_CollapseDuplicateMessages_Name {
            get {
                return ResourceManager.GetString("Options_CollapseDuplicateMessages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The side of {0} to display help for commands on..
        /// </summary>
        internal static string Options_CommandHelpSide_Description {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command help side.
        /// </summary>
        internal static string Options_CommandHelpSide_Name {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Options_Database_Advanced {
            get {
                return ResourceManager.GetString("Options_Database_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not click these buttons unless you know what you&apos;re doing..
        /// </summary>
        internal static string Options_Database_Advanced_Warning {
            get {
                return ResourceManager.GetString("Options_Database_Advanced_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Options_Database_Tab {
            get {
                return ResourceManager.GetString("Options_Database_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If battle messages are saved to the database, the size of the database will grow much faster, and there will be a noticeable freeze when saving settings. It is recommended to leave this disabled..
        /// </summary>
        internal static string Options_DatabaseBattleMessages_Description {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save battle messages in database.
        /// </summary>
        internal static string Options_DatabaseBattleMessages_Name {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Options_Display_Tab {
            get {
                return ResourceManager.GetString("Options_Display_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra glyphs can be added to {0}&apos;s global font by enabling the checkboxes below. This will likely require increasing Dalamud&apos;s font atlas size..
        /// </summary>
        internal static string Options_ExtraGlyphs_Description {
            get {
                return ResourceManager.GetString("Options_ExtraGlyphs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra font glyphs.
        /// </summary>
        internal static string Options_ExtraGlyphs_Name {
            get {
                return ResourceManager.GetString("Options_ExtraGlyphs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include messages from before the game was launched when populating tabs. Tabs are populated when the settings are saved..
        /// </summary>
        internal static string Options_FilterIncludePreviousSessions_Description {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include previous sessions when populating tabs.
        /// </summary>
        internal static string Options_FilterIncludePreviousSessions_Name {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font {0} will use to display non-Japanese text..
        /// </summary>
        internal static string Options_Font_Description {
            get {
                return ResourceManager.GetString("Options_Font_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Options_Font_Name {
            get {
                return ResourceManager.GetString("Options_Font_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using certain system fonts may crash your game. You have been warned..
        /// </summary>
        internal static string Options_Font_Warning {
            get {
                return ResourceManager.GetString("Options_Font_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Options_Fonts_Tab {
            get {
                return ResourceManager.GetString("Options_Fonts_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom fonts.
        /// </summary>
        internal static string Options_FontsEnabled {
            get {
                return ResourceManager.GetString("Options_FontsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Options_FontSize_Name {
            get {
                return ResourceManager.GetString("Options_FontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the in-game chat window when the plugin is active..
        /// </summary>
        internal static string Options_HideChat_Description {
            get {
                return ResourceManager.GetString("Options_HideChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide vanilla chat.
        /// </summary>
        internal static string Options_HideChat_Name {
            get {
                return ResourceManager.GetString("Options_HideChat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} during cutscenes..
        /// </summary>
        internal static string Options_HideDuringCutscenes_Description {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide chat during cutscenes.
        /// </summary>
        internal static string Options_HideDuringCutscenes_Name {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide timestamps when previous messages have the same timestamp..
        /// </summary>
        internal static string Options_HideSameTimestamps_Description {
            get {
                return ResourceManager.GetString("Options_HideSameTimestamps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide timestamps when redundant.
        /// </summary>
        internal static string Options_HideSameTimestamps_Name {
            get {
                return ResourceManager.GetString("Options_HideSameTimestamps_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} when you are not logged in to a character..
        /// </summary>
        internal static string Options_HideWhenNotLoggedIn_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when not logged in.
        /// </summary>
        internal static string Options_HideWhenNotLoggedIn_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} when the game UI is hidden..
        /// </summary>
        internal static string Options_HideWhenUiHidden_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when game UI is hidden.
        /// </summary>
        internal static string Options_HideWhenUiHidden_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font {0} will use to display Japanese text..
        /// </summary>
        internal static string Options_JapaneseFont_Description {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese font.
        /// </summary>
        internal static string Options_JapaneseFont_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese font size.
        /// </summary>
        internal static string Options_JapaneseFontSize_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way in which {0} should handle keybinds..
        /// </summary>
        internal static string Options_KeybindMode_Description {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind mode.
        /// </summary>
        internal static string Options_KeybindMode_Name {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language to display {0} in..
        /// </summary>
        internal static string Options_Language_Description {
            get {
                return ResourceManager.GetString("Options_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Options_Language_Name {
            get {
                return ResourceManager.GetString("Options_Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After logging in, populate the chat with the messages from when you last logged off..
        /// </summary>
        internal static string Options_LoadPreviousSession_Description {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display previous chat session on login.
        /// </summary>
        internal static string Options_LoadPreviousSession_Name {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Options_Miscellaneous_Tab {
            get {
                return ResourceManager.GetString("Options_Miscellaneous_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the spacing between messages..
        /// </summary>
        internal static string Options_MoreCompactPretty_Description {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More compact modern layout.
        /// </summary>
        internal static string Options_MoreCompactPretty_Name {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in-game item tooltips when hovering over items in {0}..
        /// </summary>
        internal static string Options_NativeItemTooltips_Description {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show native item tooltips.
        /// </summary>
        internal static string Options_NativeItemTooltips_Name {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display messages in a more modern style..
        /// </summary>
        internal static string Options_PrettierTimestamps_Description {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use modern layout.
        /// </summary>
        internal static string Options_PrettierTimestamps_Name {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple clients to run {0} at the same time, sharing the same database..
        /// </summary>
        internal static string Options_SharedMode_Description {
            get {
                return ResourceManager.GetString("Options_SharedMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable multi-client mode.
        /// </summary>
        internal static string Options_SharedMode_Name {
            get {
                return ResourceManager.GetString("Options_SharedMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is not recommended. No support will be offered if you enable this option. This option will hurt the performance of {0}..
        /// </summary>
        internal static string Options_SharedMode_Warning {
            get {
                return ResourceManager.GetString("Options_SharedMode_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Novice Network join button next to the settings button if logged in as a mentor..
        /// </summary>
        internal static string Options_ShowNoviceNetwork_Description {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Novice Network join button.
        /// </summary>
        internal static string Options_ShowNoviceNetwork_Name {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title bar for popped-out tabs.
        /// </summary>
        internal static string Options_ShowPopOutTitleBar_Name {
            get {
                return ResourceManager.GetString("Options_ShowPopOutTitleBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title bar for chat.
        /// </summary>
        internal static string Options_ShowTitleBar_Name {
            get {
                return ResourceManager.GetString("Options_ShowTitleBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs in {0} as a sidebar instead of a bar at the top..
        /// </summary>
        internal static string Options_SidebarTabView_Description {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs in a sidebar.
        /// </summary>
        internal static string Options_SidebarTabView_Name {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is enabled, the Auto Translate list will be sorted alphabetically..
        /// </summary>
        internal static string Options_SortAutoTranslate_Description {
            get {
                return ResourceManager.GetString("Options_SortAutoTranslate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort the Auto Translate list.
        /// </summary>
        internal static string Options_SortAutoTranslate_Name {
            get {
                return ResourceManager.GetString("Options_SortAutoTranslate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size to use for game symbols..
        /// </summary>
        internal static string Options_SymbolsFontSize_Description {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols font size.
        /// </summary>
        internal static string Options_SymbolsFontSize_Name {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Options_Tabs_Add {
            get {
                return ResourceManager.GetString("Options_Tabs_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Options_Tabs_Channels {
            get {
                return ResourceManager.GetString("Options_Tabs_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Announcements {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Battle {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Chat {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Special {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Options_Tabs_Delete {
            get {
                return ResourceManager.GetString("Options_Tabs_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different opacity than main window.
        /// </summary>
        internal static string Options_Tabs_IndependentOpacity {
            get {
                return ResourceManager.GetString("Options_Tabs_IndependentOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input channel.
        /// </summary>
        internal static string Options_Tabs_InputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_InputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string Options_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string Options_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Options_Tabs_Name {
            get {
                return ResourceManager.GetString("Options_Tabs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string Options_Tabs_NewTab {
            get {
                return ResourceManager.GetString("Options_Tabs_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string Options_Tabs_NoInputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_NoInputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Options_Tabs_Opacity {
            get {
                return ResourceManager.GetString("Options_Tabs_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display in separate window.
        /// </summary>
        internal static string Options_Tabs_PopOut {
            get {
                return ResourceManager.GetString("Options_Tabs_PopOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset: {0}.
        /// </summary>
        internal static string Options_Tabs_Preset {
            get {
                return ResourceManager.GetString("Options_Tabs_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        internal static string Options_Tabs_ShowTimestamps {
            get {
                return ResourceManager.GetString("Options_Tabs_ShowTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string Options_Tabs_Tab {
            get {
                return ResourceManager.GetString("Options_Tabs_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread mode.
        /// </summary>
        internal static string Options_Tabs_UnreadMode {
            get {
                return ResourceManager.GetString("Options_Tabs_UnreadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window opacity.
        /// </summary>
        internal static string Options_WindowOpacity_Name {
            get {
                return ResourceManager.GetString("Options_WindowOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Settings_Discard {
            get {
                return ResourceManager.GetString("Settings_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support {0} on Ko-fi.
        /// </summary>
        internal static string Settings_Kofi {
            get {
                return ResourceManager.GetString("Settings_Kofi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        internal static string Settings_SaveAndClose {
            get {
                return ResourceManager.GetString("Settings_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string Tab_DefaultName {
            get {
                return ResourceManager.GetString("Tab_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Tabs_Presets_Event {
            get {
                return ResourceManager.GetString("Tabs_Presets_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Tabs_Presets_General {
            get {
                return ResourceManager.GetString("Tabs_Presets_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string UnreadMode_All {
            get {
                return ResourceManager.GetString("UnreadMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show unread indicators..
        /// </summary>
        internal static string UnreadMode_All_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_All_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string UnreadMode_None {
            get {
                return ResourceManager.GetString("UnreadMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show unread indicators..
        /// </summary>
        internal static string UnreadMode_None_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_None_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseen.
        /// </summary>
        internal static string UnreadMode_Unseen {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show unread indicators for messages you haven&apos;t seen..
        /// </summary>
        internal static string UnreadMode_Unseen_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen_Tooltip", resourceCulture);
            }
        }
    }
}
