//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTwo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatTwo.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide chat.
        /// </summary>
        internal static string ChatLog_HideChat {
            get {
                return ResourceManager.GetString("ChatLog_HideChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled for this tab..
        /// </summary>
        internal static string ChatLog_SwitcherDisabled {
            get {
                return ResourceManager.GetString("ChatLog_SwitcherDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tab.
        /// </summary>
        internal static string ChatLog_Tabs_Delete {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string ChatLog_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        internal static string ChatLog_Tabs_MoveLeft {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        internal static string ChatLog_Tabs_MoveRight {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string ChatLog_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Member.
        /// </summary>
        internal static string ChatSource_AllianceMember {
            get {
                return ResourceManager.GetString("ChatSource_AllianceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Alliance member).
        /// </summary>
        internal static string ChatSource_AlliancePet {
            get {
                return ResourceManager.GetString("ChatSource_AlliancePet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged Enemy.
        /// </summary>
        internal static string ChatSource_EngagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_EngagedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly NPC.
        /// </summary>
        internal static string ChatSource_FriendlyNpc {
            get {
                return ResourceManager.GetString("ChatSource_FriendlyNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ChatSource_Other {
            get {
                return ResourceManager.GetString("ChatSource_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Other).
        /// </summary>
        internal static string ChatSource_OtherPet {
            get {
                return ResourceManager.GetString("ChatSource_OtherPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Member.
        /// </summary>
        internal static string ChatSource_PartyMember {
            get {
                return ResourceManager.GetString("ChatSource_PartyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Party).
        /// </summary>
        internal static string ChatSource_PartyPet {
            get {
                return ResourceManager.GetString("ChatSource_PartyPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string ChatSource_Self {
            get {
                return ResourceManager.GetString("ChatSource_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet (Self).
        /// </summary>
        internal static string ChatSource_SelfPet {
            get {
                return ResourceManager.GetString("ChatSource_SelfPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unengaged Enemy.
        /// </summary>
        internal static string ChatSource_UnengagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_UnengagedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string CommandHelpSide_Left {
            get {
                return ResourceManager.GetString("CommandHelpSide_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CommandHelpSide_None {
            get {
                return ResourceManager.GetString("CommandHelpSide_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string CommandHelpSide_Right {
            get {
                return ResourceManager.GetString("CommandHelpSide_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible.
        /// </summary>
        internal static string KeybindMode_Flexible_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process keybinds with modifiers even if other modifiers are pressed..
        /// </summary>
        internal static string KeybindMode_Flexible_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        internal static string KeybindMode_Strict_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only process keybinds with modifiers if no other modifiers are pressed..
        /// </summary>
        internal static string KeybindMode_Strict_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dalamud&apos;s default language.
        /// </summary>
        internal static string LanguageOverride_None {
            get {
                return ResourceManager.GetString("LanguageOverride_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to the left to see what&apos;s being worked on and what&apos;s next..
        /// </summary>
        internal static string Options_About_ClickUp {
            get {
                return ResourceManager.GetString("Options_About_ClickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to the left to help translate {0}..
        /// </summary>
        internal static string Options_About_CrowdIn {
            get {
                return ResourceManager.GetString("Options_About_CrowdIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a project to completely recreate the in-game chat and make it even better..
        /// </summary>
        internal static string Options_About_Opening {
            get {
                return ResourceManager.GetString("Options_About_Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Options_About_Tab {
            get {
                return ResourceManager.GetString("Options_About_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        internal static string Options_About_Translators {
            get {
                return ResourceManager.GetString("Options_About_Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving chat.
        /// </summary>
        internal static string Options_CanMove_Name {
            get {
                return ResourceManager.GetString("Options_CanMove_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow resizing chat.
        /// </summary>
        internal static string Options_CanResize_Name {
            get {
                return ResourceManager.GetString("Options_CanResize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from game.
        /// </summary>
        internal static string Options_ChatColours_Import {
            get {
                return ResourceManager.GetString("Options_ChatColours_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        internal static string Options_ChatColours_Reset {
            get {
                return ResourceManager.GetString("Options_ChatColours_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat colours.
        /// </summary>
        internal static string Options_ChatColours_Tab {
            get {
                return ResourceManager.GetString("Options_ChatColours_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The side of {0} to display help for commands on..
        /// </summary>
        internal static string Options_CommandHelpSide_Description {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command help side.
        /// </summary>
        internal static string Options_CommandHelpSide_Name {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Options_Database_Tab {
            get {
                return ResourceManager.GetString("Options_Database_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If battle messages are saved to the database, the size of the database will grow much faster, and there will be a noticeable freeze when saving settings. It is recommended to leave this disabled..
        /// </summary>
        internal static string Options_DatabaseBattleMessages_Description {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save battle messages in database.
        /// </summary>
        internal static string Options_DatabaseBattleMessages_Name {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Options_Display_Tab {
            get {
                return ResourceManager.GetString("Options_Display_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include messages from before the game was launched when populating tabs. Tabs are populated when the settings are saved..
        /// </summary>
        internal static string Options_FilterIncludePreviousSessions_Description {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include previous sessions when populating tabs.
        /// </summary>
        internal static string Options_FilterIncludePreviousSessions_Name {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font {0} will use to display non-Japanese text..
        /// </summary>
        internal static string Options_Font_Description {
            get {
                return ResourceManager.GetString("Options_Font_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Options_Font_Name {
            get {
                return ResourceManager.GetString("Options_Font_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using certain system fonts may crash your game. You have been warned..
        /// </summary>
        internal static string Options_Font_Warning {
            get {
                return ResourceManager.GetString("Options_Font_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Options_Fonts_Tab {
            get {
                return ResourceManager.GetString("Options_Fonts_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Options_FontSize_Name {
            get {
                return ResourceManager.GetString("Options_FontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the in-game chat window when the plugin is active..
        /// </summary>
        internal static string Options_HideChat_Description {
            get {
                return ResourceManager.GetString("Options_HideChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide vanilla chat.
        /// </summary>
        internal static string Options_HideChat_Name {
            get {
                return ResourceManager.GetString("Options_HideChat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} during cutscenes..
        /// </summary>
        internal static string Options_HideDuringCutscenes_Description {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide chat during cutscenes.
        /// </summary>
        internal static string Options_HideDuringCutscenes_Name {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} when you are not logged in to a character..
        /// </summary>
        internal static string Options_HideWhenNotLoggedIn_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when not logged in.
        /// </summary>
        internal static string Options_HideWhenNotLoggedIn_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} when the game UI is hidden..
        /// </summary>
        internal static string Options_HideWhenUiHidden_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when game UI is hidden.
        /// </summary>
        internal static string Options_HideWhenUiHidden_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font {0} will use to display Japanese text..
        /// </summary>
        internal static string Options_JapaneseFont_Description {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese font.
        /// </summary>
        internal static string Options_JapaneseFont_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese font size.
        /// </summary>
        internal static string Options_JapaneseFontSize_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way in which {0} should handle keybinds..
        /// </summary>
        internal static string Options_KeybindMode_Description {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind mode.
        /// </summary>
        internal static string Options_KeybindMode_Name {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language to display {0} in..
        /// </summary>
        internal static string Options_Language_Description {
            get {
                return ResourceManager.GetString("Options_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Options_Language_Name {
            get {
                return ResourceManager.GetString("Options_Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After logging in, populate the chat with the messages from when you last logged off..
        /// </summary>
        internal static string Options_LoadPreviousSession_Description {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display previous chat session on login.
        /// </summary>
        internal static string Options_LoadPreviousSession_Name {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Options_Miscellaneous_Tab {
            get {
                return ResourceManager.GetString("Options_Miscellaneous_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the spacing between messages..
        /// </summary>
        internal static string Options_MoreCompactPretty_Description {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More compact modern layout.
        /// </summary>
        internal static string Options_MoreCompactPretty_Name {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in-game item tooltips when hovering over items in {0}..
        /// </summary>
        internal static string Options_NativeItemTooltips_Description {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show native item tooltips.
        /// </summary>
        internal static string Options_NativeItemTooltips_Name {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a more modern style of displaying messages..
        /// </summary>
        internal static string Options_PrettierTimestamps_Description {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use modern timestamp layout.
        /// </summary>
        internal static string Options_PrettierTimestamps_Name {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Novice Network join button next to the settings button if logged in as a mentor..
        /// </summary>
        internal static string Options_ShowNoviceNetwork_Description {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Novice Network join button.
        /// </summary>
        internal static string Options_ShowNoviceNetwork_Name {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title bar for chat.
        /// </summary>
        internal static string Options_ShowTitleBar_Name {
            get {
                return ResourceManager.GetString("Options_ShowTitleBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs in {0} as a sidebar instead of a bar at the top..
        /// </summary>
        internal static string Options_SidebarTabView_Description {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs in a sidebar.
        /// </summary>
        internal static string Options_SidebarTabView_Name {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size to use for game symbols..
        /// </summary>
        internal static string Options_SymbolsFontSize_Description {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols font size.
        /// </summary>
        internal static string Options_SymbolsFontSize_Name {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Options_Tabs_Add {
            get {
                return ResourceManager.GetString("Options_Tabs_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Options_Tabs_Channels {
            get {
                return ResourceManager.GetString("Options_Tabs_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Announcements {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Battle {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Chat {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Options_Tabs_ChannelTypes_Special {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Options_Tabs_Delete {
            get {
                return ResourceManager.GetString("Options_Tabs_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input channel.
        /// </summary>
        internal static string Options_Tabs_InputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_InputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string Options_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string Options_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Options_Tabs_Name {
            get {
                return ResourceManager.GetString("Options_Tabs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string Options_Tabs_NewTab {
            get {
                return ResourceManager.GetString("Options_Tabs_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string Options_Tabs_NoInputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_NoInputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset: {0}.
        /// </summary>
        internal static string Options_Tabs_Preset {
            get {
                return ResourceManager.GetString("Options_Tabs_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        internal static string Options_Tabs_ShowTimestamps {
            get {
                return ResourceManager.GetString("Options_Tabs_ShowTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string Options_Tabs_Tab {
            get {
                return ResourceManager.GetString("Options_Tabs_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread mode.
        /// </summary>
        internal static string Options_Tabs_UnreadMode {
            get {
                return ResourceManager.GetString("Options_Tabs_UnreadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window opacity.
        /// </summary>
        internal static string Options_WindowOpacity_Name {
            get {
                return ResourceManager.GetString("Options_WindowOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Settings_Discard {
            get {
                return ResourceManager.GetString("Settings_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support {0} on Ko-fi.
        /// </summary>
        internal static string Settings_Kofi {
            get {
                return ResourceManager.GetString("Settings_Kofi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        internal static string Settings_SaveAndClose {
            get {
                return ResourceManager.GetString("Settings_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string Tab_DefaultName {
            get {
                return ResourceManager.GetString("Tab_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Tabs_Presets_Event {
            get {
                return ResourceManager.GetString("Tabs_Presets_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Tabs_Presets_General {
            get {
                return ResourceManager.GetString("Tabs_Presets_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string UnreadMode_All {
            get {
                return ResourceManager.GetString("UnreadMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show unread indicators..
        /// </summary>
        internal static string UnreadMode_All_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_All_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string UnreadMode_None {
            get {
                return ResourceManager.GetString("UnreadMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show unread indicators..
        /// </summary>
        internal static string UnreadMode_None_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_None_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseen.
        /// </summary>
        internal static string UnreadMode_Unseen {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show unread indicators for messages you haven&apos;t seen..
        /// </summary>
        internal static string UnreadMode_Unseen_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen_Tooltip", resourceCulture);
            }
        }
    }
}
