//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTwo.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChatTwo.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Options_HideChat_Name {
            get {
                return ResourceManager.GetString("Options_HideChat_Name", resourceCulture);
            }
        }
        
        internal static string Options_HideChat_Description {
            get {
                return ResourceManager.GetString("Options_HideChat_Description", resourceCulture);
            }
        }
        
        internal static string Options_HideDuringCutscenes_Name {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Name", resourceCulture);
            }
        }
        
        internal static string Options_HideDuringCutscenes_Description {
            get {
                return ResourceManager.GetString("Options_HideDuringCutscenes_Description", resourceCulture);
            }
        }
        
        internal static string Options_NativeItemTooltips_Name {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Name", resourceCulture);
            }
        }
        
        internal static string Options_NativeItemTooltips_Description {
            get {
                return ResourceManager.GetString("Options_NativeItemTooltips_Description", resourceCulture);
            }
        }
        
        internal static string Options_SidebarTabView_Name {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Name", resourceCulture);
            }
        }
        
        internal static string Options_SidebarTabView_Description {
            get {
                return ResourceManager.GetString("Options_SidebarTabView_Description", resourceCulture);
            }
        }
        
        internal static string Options_PrettierTimestamps_Name {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Name", resourceCulture);
            }
        }
        
        internal static string Options_PrettierTimestamps_Description {
            get {
                return ResourceManager.GetString("Options_PrettierTimestamps_Description", resourceCulture);
            }
        }
        
        internal static string Options_MoreCompactPretty_Name {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Name", resourceCulture);
            }
        }
        
        internal static string Options_MoreCompactPretty_Description {
            get {
                return ResourceManager.GetString("Options_MoreCompactPretty_Description", resourceCulture);
            }
        }
        
        internal static string Options_ShowNoviceNetwork_Name {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Name", resourceCulture);
            }
        }
        
        internal static string Options_ShowNoviceNetwork_Description {
            get {
                return ResourceManager.GetString("Options_ShowNoviceNetwork_Description", resourceCulture);
            }
        }
        
        internal static string Options_FontSize_Name {
            get {
                return ResourceManager.GetString("Options_FontSize_Name", resourceCulture);
            }
        }
        
        internal static string Options_WindowOpacity_Name {
            get {
                return ResourceManager.GetString("Options_WindowOpacity_Name", resourceCulture);
            }
        }
        
        internal static string Options_CanMove_Name {
            get {
                return ResourceManager.GetString("Options_CanMove_Name", resourceCulture);
            }
        }
        
        internal static string Options_CanResize_Name {
            get {
                return ResourceManager.GetString("Options_CanResize_Name", resourceCulture);
            }
        }
        
        internal static string Options_ShowTitleBar_Name {
            get {
                return ResourceManager.GetString("Options_ShowTitleBar_Name", resourceCulture);
            }
        }
        
        internal static string Options_Display_Tab {
            get {
                return ResourceManager.GetString("Options_Display_Tab", resourceCulture);
            }
        }
        
        internal static string Options_ChatColours_Tab {
            get {
                return ResourceManager.GetString("Options_ChatColours_Tab", resourceCulture);
            }
        }
        
        internal static string Options_ChatColours_Reset {
            get {
                return ResourceManager.GetString("Options_ChatColours_Reset", resourceCulture);
            }
        }
        
        internal static string Options_ChatColours_Import {
            get {
                return ResourceManager.GetString("Options_ChatColours_Import", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Tab {
            get {
                return ResourceManager.GetString("Options_Tabs_Tab", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Add {
            get {
                return ResourceManager.GetString("Options_Tabs_Add", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Delete {
            get {
                return ResourceManager.GetString("Options_Tabs_Delete", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveUp", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("Options_Tabs_MoveDown", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Name {
            get {
                return ResourceManager.GetString("Options_Tabs_Name", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_ShowTimestamps {
            get {
                return ResourceManager.GetString("Options_Tabs_ShowTimestamps", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_UnreadMode {
            get {
                return ResourceManager.GetString("Options_Tabs_UnreadMode", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_NoInputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_NoInputChannel", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_InputChannel {
            get {
                return ResourceManager.GetString("Options_Tabs_InputChannel", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Channels {
            get {
                return ResourceManager.GetString("Options_Tabs_Channels", resourceCulture);
            }
        }
        
        internal static string UnreadMode_All_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_All_Tooltip", resourceCulture);
            }
        }
        
        internal static string UnreadMode_Unseen_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen_Tooltip", resourceCulture);
            }
        }
        
        internal static string UnreadMode_None_Tooltip {
            get {
                return ResourceManager.GetString("UnreadMode_None_Tooltip", resourceCulture);
            }
        }
        
        internal static string Tab_DefaultName {
            get {
                return ResourceManager.GetString("Tab_DefaultName", resourceCulture);
            }
        }
        
        internal static string Settings_Kofi {
            get {
                return ResourceManager.GetString("Settings_Kofi", resourceCulture);
            }
        }
        
        internal static string Settings_SaveAndClose {
            get {
                return ResourceManager.GetString("Settings_SaveAndClose", resourceCulture);
            }
        }
        
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        internal static string Settings_Discard {
            get {
                return ResourceManager.GetString("Settings_Discard", resourceCulture);
            }
        }
        
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        internal static string ChatLog_SwitcherDisabled {
            get {
                return ResourceManager.GetString("ChatLog_SwitcherDisabled", resourceCulture);
            }
        }
        
        internal static string ChatLog_HideChat {
            get {
                return ResourceManager.GetString("ChatLog_HideChat", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_MoveUp {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveUp", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_MoveLeft {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveLeft", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_MoveDown {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveDown", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_MoveRight {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_MoveRight", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_ChannelTypes_Chat {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Chat", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_ChannelTypes_Battle {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Battle", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_ChannelTypes_Announcements {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Announcements", resourceCulture);
            }
        }
        
        internal static string UnreadMode_All {
            get {
                return ResourceManager.GetString("UnreadMode_All", resourceCulture);
            }
        }
        
        internal static string UnreadMode_Unseen {
            get {
                return ResourceManager.GetString("UnreadMode_Unseen", resourceCulture);
            }
        }
        
        internal static string UnreadMode_None {
            get {
                return ResourceManager.GetString("UnreadMode_None", resourceCulture);
            }
        }
        
        internal static string ChatSource_Self {
            get {
                return ResourceManager.GetString("ChatSource_Self", resourceCulture);
            }
        }
        
        internal static string ChatSource_PartyMember {
            get {
                return ResourceManager.GetString("ChatSource_PartyMember", resourceCulture);
            }
        }
        
        internal static string ChatSource_AllianceMember {
            get {
                return ResourceManager.GetString("ChatSource_AllianceMember", resourceCulture);
            }
        }
        
        internal static string ChatSource_Other {
            get {
                return ResourceManager.GetString("ChatSource_Other", resourceCulture);
            }
        }
        
        internal static string ChatSource_EngagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_EngagedEnemy", resourceCulture);
            }
        }
        
        internal static string ChatSource_UnengagedEnemy {
            get {
                return ResourceManager.GetString("ChatSource_UnengagedEnemy", resourceCulture);
            }
        }
        
        internal static string ChatSource_FriendlyNpc {
            get {
                return ResourceManager.GetString("ChatSource_FriendlyNpc", resourceCulture);
            }
        }
        
        internal static string ChatSource_SelfPet {
            get {
                return ResourceManager.GetString("ChatSource_SelfPet", resourceCulture);
            }
        }
        
        internal static string ChatSource_PartyPet {
            get {
                return ResourceManager.GetString("ChatSource_PartyPet", resourceCulture);
            }
        }
        
        internal static string ChatSource_AlliancePet {
            get {
                return ResourceManager.GetString("ChatSource_AlliancePet", resourceCulture);
            }
        }
        
        internal static string ChatSource_OtherPet {
            get {
                return ResourceManager.GetString("ChatSource_OtherPet", resourceCulture);
            }
        }
        
        internal static string Options_Font_Name {
            get {
                return ResourceManager.GetString("Options_Font_Name", resourceCulture);
            }
        }
        
        internal static string Options_JapaneseFont_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Name", resourceCulture);
            }
        }
        
        internal static string Options_Font_Description {
            get {
                return ResourceManager.GetString("Options_Font_Description", resourceCulture);
            }
        }
        
        internal static string Options_Font_Warning {
            get {
                return ResourceManager.GetString("Options_Font_Warning", resourceCulture);
            }
        }
        
        internal static string Options_JapaneseFont_Description {
            get {
                return ResourceManager.GetString("Options_JapaneseFont_Description", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_ChannelTypes_Special {
            get {
                return ResourceManager.GetString("Options_Tabs_ChannelTypes_Special", resourceCulture);
            }
        }
        
        internal static string Options_Fonts_Tab {
            get {
                return ResourceManager.GetString("Options_Fonts_Tab", resourceCulture);
            }
        }
        
        internal static string Options_SymbolsFontSize_Name {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Name", resourceCulture);
            }
        }
        
        internal static string Options_JapaneseFontSize_Name {
            get {
                return ResourceManager.GetString("Options_JapaneseFontSize_Name", resourceCulture);
            }
        }
        
        internal static string Options_SymbolsFontSize_Description {
            get {
                return ResourceManager.GetString("Options_SymbolsFontSize_Description", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_Delete {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_Delete", resourceCulture);
            }
        }
        
        internal static string Options_HideWhenNotLoggedIn_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Name", resourceCulture);
            }
        }
        
        internal static string Options_HideWhenNotLoggedIn_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenNotLoggedIn_Description", resourceCulture);
            }
        }
        
        internal static string Tabs_Presets_General {
            get {
                return ResourceManager.GetString("Tabs_Presets_General", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Preset {
            get {
                return ResourceManager.GetString("Options_Tabs_Preset", resourceCulture);
            }
        }
        
        internal static string Tabs_Presets_Event {
            get {
                return ResourceManager.GetString("Tabs_Presets_Event", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_NewTab {
            get {
                return ResourceManager.GetString("Options_Tabs_NewTab", resourceCulture);
            }
        }
        
        internal static string Options_About_Tab {
            get {
                return ResourceManager.GetString("Options_About_Tab", resourceCulture);
            }
        }
        
        internal static string Options_About_Opening {
            get {
                return ResourceManager.GetString("Options_About_Opening", resourceCulture);
            }
        }
        
        internal static string Options_About_ClickUp {
            get {
                return ResourceManager.GetString("Options_About_ClickUp", resourceCulture);
            }
        }
        
        internal static string Options_About_CrowdIn {
            get {
                return ResourceManager.GetString("Options_About_CrowdIn", resourceCulture);
            }
        }
        
        internal static string Options_About_Translators {
            get {
                return ResourceManager.GetString("Options_About_Translators", resourceCulture);
            }
        }
        
        internal static string CommandHelpSide_None {
            get {
                return ResourceManager.GetString("CommandHelpSide_None", resourceCulture);
            }
        }
        
        internal static string CommandHelpSide_Left {
            get {
                return ResourceManager.GetString("CommandHelpSide_Left", resourceCulture);
            }
        }
        
        internal static string CommandHelpSide_Right {
            get {
                return ResourceManager.GetString("CommandHelpSide_Right", resourceCulture);
            }
        }
        
        internal static string Options_CommandHelpSide_Name {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Name", resourceCulture);
            }
        }
        
        internal static string Options_CommandHelpSide_Description {
            get {
                return ResourceManager.GetString("Options_CommandHelpSide_Description", resourceCulture);
            }
        }
        
        internal static string Options_HideWhenUiHidden_Name {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Name", resourceCulture);
            }
        }
        
        internal static string Options_HideWhenUiHidden_Description {
            get {
                return ResourceManager.GetString("Options_HideWhenUiHidden_Description", resourceCulture);
            }
        }
        
        internal static string Options_KeybindMode_Name {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Name", resourceCulture);
            }
        }
        
        internal static string Options_KeybindMode_Description {
            get {
                return ResourceManager.GetString("Options_KeybindMode_Description", resourceCulture);
            }
        }
        
        internal static string Options_Miscellaneous_Tab {
            get {
                return ResourceManager.GetString("Options_Miscellaneous_Tab", resourceCulture);
            }
        }
        
        internal static string LanguageOverride_None {
            get {
                return ResourceManager.GetString("LanguageOverride_None", resourceCulture);
            }
        }
        
        internal static string KeybindMode_Flexible_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Name", resourceCulture);
            }
        }
        
        internal static string KeybindMode_Strict_Name {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Name", resourceCulture);
            }
        }
        
        internal static string KeybindMode_Flexible_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Flexible_Tooltip", resourceCulture);
            }
        }
        
        internal static string KeybindMode_Strict_Tooltip {
            get {
                return ResourceManager.GetString("KeybindMode_Strict_Tooltip", resourceCulture);
            }
        }
        
        internal static string Options_Language_Name {
            get {
                return ResourceManager.GetString("Options_Language_Name", resourceCulture);
            }
        }
        
        internal static string Options_Language_Description {
            get {
                return ResourceManager.GetString("Options_Language_Description", resourceCulture);
            }
        }
        
        internal static string Options_DatabaseBattleMessages_Name {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Name", resourceCulture);
            }
        }
        
        internal static string Options_DatabaseBattleMessages_Description {
            get {
                return ResourceManager.GetString("Options_DatabaseBattleMessages_Description", resourceCulture);
            }
        }
        
        internal static string Options_LoadPreviousSession_Name {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Name", resourceCulture);
            }
        }
        
        internal static string Options_LoadPreviousSession_Description {
            get {
                return ResourceManager.GetString("Options_LoadPreviousSession_Description", resourceCulture);
            }
        }
        
        internal static string Options_Database_Tab {
            get {
                return ResourceManager.GetString("Options_Database_Tab", resourceCulture);
            }
        }
        
        internal static string Options_FilterIncludePreviousSessions_Name {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Name", resourceCulture);
            }
        }
        
        internal static string Options_FilterIncludePreviousSessions_Description {
            get {
                return ResourceManager.GetString("Options_FilterIncludePreviousSessions_Description", resourceCulture);
            }
        }
        
        internal static string Options_Database_Advanced_Warning {
            get {
                return ResourceManager.GetString("Options_Database_Advanced_Warning", resourceCulture);
            }
        }
        
        internal static string Options_Database_Advanced {
            get {
                return ResourceManager.GetString("Options_Database_Advanced", resourceCulture);
            }
        }
        
        internal static string Options_SharedMode_Name {
            get {
                return ResourceManager.GetString("Options_SharedMode_Name", resourceCulture);
            }
        }
        
        internal static string Options_SharedMode_Description {
            get {
                return ResourceManager.GetString("Options_SharedMode_Description", resourceCulture);
            }
        }
        
        internal static string Options_SharedMode_Warning {
            get {
                return ResourceManager.GetString("Options_SharedMode_Warning", resourceCulture);
            }
        }
        
        internal static string ChatLog_Tabs_PopOut {
            get {
                return ResourceManager.GetString("ChatLog_Tabs_PopOut", resourceCulture);
            }
        }
        
        internal static string Options_HideSameTimestamps_Name {
            get {
                return ResourceManager.GetString("Options_HideSameTimestamps_Name", resourceCulture);
            }
        }
        
        internal static string Options_HideSameTimestamps_Description {
            get {
                return ResourceManager.GetString("Options_HideSameTimestamps_Description", resourceCulture);
            }
        }
        
        internal static string Options_ShowPopOutTitleBar_Name {
            get {
                return ResourceManager.GetString("Options_ShowPopOutTitleBar_Name", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_PopOut {
            get {
                return ResourceManager.GetString("Options_Tabs_PopOut", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_IndependentOpacity {
            get {
                return ResourceManager.GetString("Options_Tabs_IndependentOpacity", resourceCulture);
            }
        }
        
        internal static string Options_Tabs_Opacity {
            get {
                return ResourceManager.GetString("Options_Tabs_Opacity", resourceCulture);
            }
        }
        
        internal static string Options_FontsEnabled {
            get {
                return ResourceManager.GetString("Options_FontsEnabled", resourceCulture);
            }
        }
        
        internal static string AutoTranslate_Search_Hint {
            get {
                return ResourceManager.GetString("AutoTranslate_Search_Hint", resourceCulture);
            }
        }
        
        internal static string Options_SortAutoTranslate_Name {
            get {
                return ResourceManager.GetString("Options_SortAutoTranslate_Name", resourceCulture);
            }
        }
        
        internal static string Options_SortAutoTranslate_Description {
            get {
                return ResourceManager.GetString("Options_SortAutoTranslate_Description", resourceCulture);
            }
        }
        
        internal static string AutoTranslate_Completion_Key {
            get {
                return ResourceManager.GetString("AutoTranslate_Completion_Key", resourceCulture);
            }
        }
        
        internal static string Options_ExtraGlyphs_Name {
            get {
                return ResourceManager.GetString("Options_ExtraGlyphs_Name", resourceCulture);
            }
        }
        
        internal static string Options_ExtraGlyphs_Description {
            get {
                return ResourceManager.GetString("Options_ExtraGlyphs_Description", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_ChineseFull_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_ChineseFull_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_ChineseSimplifiedCommon_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_ChineseSimplifiedCommon_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_Cyrillic_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Cyrillic_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_Japanese_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Japanese_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_Korean_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Korean_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_Thai_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Thai_Name", resourceCulture);
            }
        }
        
        internal static string ExtraGlyphRanges_Vietnamese_Name {
            get {
                return ResourceManager.GetString("ExtraGlyphRanges_Vietnamese_Name", resourceCulture);
            }
        }
        
        internal static string Context_Integrations {
            get {
                return ResourceManager.GetString("Context_Integrations", resourceCulture);
            }
        }
        
        internal static string Context_ScreenshotMode {
            get {
                return ResourceManager.GetString("Context_ScreenshotMode", resourceCulture);
            }
        }
        
        internal static string Context_HideChat {
            get {
                return ResourceManager.GetString("Context_HideChat", resourceCulture);
            }
        }
        
        internal static string Context_Copy {
            get {
                return ResourceManager.GetString("Context_Copy", resourceCulture);
            }
        }
        
        internal static string Context_TryOn {
            get {
                return ResourceManager.GetString("Context_TryOn", resourceCulture);
            }
        }
        
        internal static string Context_ItemComparison {
            get {
                return ResourceManager.GetString("Context_ItemComparison", resourceCulture);
            }
        }
        
        internal static string Context_SearchRecipes {
            get {
                return ResourceManager.GetString("Context_SearchRecipes", resourceCulture);
            }
        }
        
        internal static string Context_SearchForItem {
            get {
                return ResourceManager.GetString("Context_SearchForItem", resourceCulture);
            }
        }
        
        internal static string Context_Link {
            get {
                return ResourceManager.GetString("Context_Link", resourceCulture);
            }
        }
        
        internal static string Context_CopyItemName {
            get {
                return ResourceManager.GetString("Context_CopyItemName", resourceCulture);
            }
        }
        
        internal static string Context_SendTell {
            get {
                return ResourceManager.GetString("Context_SendTell", resourceCulture);
            }
        }
        
        internal static string Context_InviteToParty {
            get {
                return ResourceManager.GetString("Context_InviteToParty", resourceCulture);
            }
        }
        
        internal static string Context_InviteToParty_SameWorld {
            get {
                return ResourceManager.GetString("Context_InviteToParty_SameWorld", resourceCulture);
            }
        }
        
        internal static string Context_InviteToParty_DifferentWorld {
            get {
                return ResourceManager.GetString("Context_InviteToParty_DifferentWorld", resourceCulture);
            }
        }
        
        internal static string Context_Promote {
            get {
                return ResourceManager.GetString("Context_Promote", resourceCulture);
            }
        }
        
        internal static string Context_KickFromParty {
            get {
                return ResourceManager.GetString("Context_KickFromParty", resourceCulture);
            }
        }
        
        internal static string Context_SendFriendRequest {
            get {
                return ResourceManager.GetString("Context_SendFriendRequest", resourceCulture);
            }
        }
        
        internal static string Context_AddToBlacklist {
            get {
                return ResourceManager.GetString("Context_AddToBlacklist", resourceCulture);
            }
        }
        
        internal static string Context_InviteToNoviceNetwork {
            get {
                return ResourceManager.GetString("Context_InviteToNoviceNetwork", resourceCulture);
            }
        }
        
        internal static string Context_ReplyInSelectedChatMode {
            get {
                return ResourceManager.GetString("Context_ReplyInSelectedChatMode", resourceCulture);
            }
        }
        
        internal static string Context_Target {
            get {
                return ResourceManager.GetString("Context_Target", resourceCulture);
            }
        }
    }
}
